/*
 * Frame.java
 *
 * Created on November 1, 2006, 3:34 PM
 */

package rsc.frontend;

import java.awt.Dimension;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultTreeModel;
import rsc.RSC;

public class MainFrame extends javax.swing.JFrame implements WindowListener {
    private DefaultTreeModel dtm;
    
    /** Creates new form Frame */
    public MainFrame() {
        this.setMinimumSize(new Dimension(700,500));
        this.setIconImage(new ImageIcon(this.getClass().getResource("/rsc/frontend/icon/logo.png")).getImage());
        this.addWindowListener(this);
        MainPanel mp=new MainPanel();
        add(mp);
        
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Remote Service Configurator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pack();
    }// </editor-fold>//GEN-END:initComponents
                    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void windowOpened(WindowEvent e) {
    }

    public void windowClosing(WindowEvent e) {
        int result=JOptionPane.showConfirmDialog(this, "do you want save?", "Save configuration", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result==JOptionPane.YES_OPTION) {
            try {
                RSC.getInstance().export();
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "could not create or write into configuration file", "Error", JOptionPane.ERROR_MESSAGE);
                RSC.log(Level.SEVERE, "configuration file doesn't seem to exist and its not possible to create", ex);
                return;
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "error writing to configuration file", "Error", JOptionPane.ERROR_MESSAGE);
                RSC.log(Level.SEVERE, "io-error", ex);
                return;
            }
        }
        System.exit(0);
    }

    public void windowClosed(WindowEvent e) {
    }

    public void windowIconified(WindowEvent e) {
    }

    public void windowDeiconified(WindowEvent e) {
    }

    public void windowActivated(WindowEvent e) {
    }

    public void windowDeactivated(WindowEvent e) {
    }
}
