/*
 * Configurator.java
 *
 * Created on September 8, 2008, 7:23 PM
 */

package rsc.backend.modules.ips.frontend;

import rsc.backend.modules.ips.IPS;
import rsc.backend.modules.ips.backend.Snortconf;

/**
 *
 * @author  wariin
 */
public class Configurator extends javax.swing.JPanel {
    private IPS ips;
    
    /** Creates new form Configurator */
    public Configurator(IPS ips) {
        this.ips=ips;
        ips.getConf().getConfs(Include.class);
        initComponents();
        tp_configurator.add(new Include(ips));
    }
    
    public void refresh() {
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tp_configurator = new javax.swing.JTabbedPane();
        b_save = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(tp_configurator, gridBagConstraints);

        b_save.setText("save Configuration");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        add(b_save, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_save;
    private javax.swing.JTabbedPane tp_configurator;
    // End of variables declaration//GEN-END:variables
    
}
