/*
 * Include.java
 *
 * Created on September 8, 2008, 7:31 PM
 */
package rsc.backend.modules.ips.frontend;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import javax.swing.filechooser.FileView;
import javax.swing.table.DefaultTableModel;
import rsc.backend.modules.ips.IPS;

/**
 *
 * @author  wariin
 */
public class Include extends javax.swing.JPanel {

    private IPS ips;
    private DefaultTableModel dtm;
    private JFileChooser jfs;
    private FileSystemView fsv;
    private FileView fv;

    /** Creates new form Include */
    public Include(IPS ips) {
        this.ips = ips;
        initComponents();
        String colNames[] = {"", "Rule Files"};

        dtm = new DefaultTableModel(colNames, 0);
        t_includes.setModel(dtm);
    }

    public void refresh() {
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        l_includes = new javax.swing.JLabel();
        sp_includes = new javax.swing.JScrollPane();
        t_includes = new javax.swing.JTable();
        b_add = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        l_includes.setText("Includes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(l_includes, gridBagConstraints);

        t_includes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        sp_includes.setViewportView(t_includes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(sp_includes, gridBagConstraints);

        b_add.setText("add File...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(b_add, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_add;
    private javax.swing.JLabel l_includes;
    private javax.swing.JScrollPane sp_includes;
    private javax.swing.JTable t_includes;
    // End of variables declaration//GEN-END:variables
}
